<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<StartupObject>MDMX_MaskCreator.Program</StartupObject>
    </PropertyGroup>
	
	<PropertyGroup>
		<IsTestProject>false</IsTestProject>
	</PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.3" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.3" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageReference Include="CsvHelper" Version="33.1.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="ReactiveUI" Version="20.1.1" />
        <PackageReference Include="SkiaSharp" Version="2.88.9" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.9" />
        <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="2.88.9" />
        <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.9" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <PropertyGroup>
        <ApplicationIcon>Assets\appicon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
</Project>
